#!/bin/bash
echo "Hostname in first node."
echo "======================"
vagrant ssh node1 -c "docker --version"
vagrant ssh node4 -c "ifconfig -a | grep inet"
echo "Hostname in second node."
echo "======================"
vagrant ssh node2 -c "docker --version"
vagrant ssh node4 -c "ifconfig -a | grep inet"
echo "Hostname in third node."
echo "======================"
vagrant ssh node3 -c "docker --version"
vagrant ssh node4 -c "ifconfig -a | grep inet"
echo "Hostname in fourth node."
echo "======================"
vagrant ssh node4 -c "docker --version"
vagrant ssh node4 -c "ifconfig -a | grep inet"
echo "Completed Series of commands"
